name: BuildAndTest

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: "1.4.8"
      - run: "sudo apt-get install -y libtagc0-dev"
      - run: "nimble build -y"
      - run: "nimble test -y"
